// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHpisf2PGOcWSo0i1TbnufL9TfQq38R0',
    appId: '1:395781812324:web:9345f3b65718f35cdeaf71',
    messagingSenderId: '395781812324',
    projectId: 'studysync-787c7',
    authDomain: 'studysync-787c7.firebaseapp.com',
    storageBucket: 'studysync-787c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7rhhgWlmurgJ8-MnLVFNC8m0UcaMy5ow',
    appId: '1:395781812324:android:a29955a1ce2d1f01deaf71',
    messagingSenderId: '395781812324',
    projectId: 'studysync-787c7',
    storageBucket: 'studysync-787c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SSdEfEBdigA8yMDBUzWH8BO3qjHzzlA',
    appId: '1:395781812324:ios:de3fa0dd11fe0e9bdeaf71',
    messagingSenderId: '395781812324',
    projectId: 'studysync-787c7',
    storageBucket: 'studysync-787c7.appspot.com',
    iosBundleId: 'com.example.studysync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SSdEfEBdigA8yMDBUzWH8BO3qjHzzlA',
    appId: '1:395781812324:ios:29f60a599e2250a7deaf71',
    messagingSenderId: '395781812324',
    projectId: 'studysync-787c7',
    storageBucket: 'studysync-787c7.appspot.com',
    iosBundleId: 'com.example.studysync.RunnerTests',
  );
}
